# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 403)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input = QtWidgets.QLabel(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(10, 20, 331, 281))
        self.input.setScaledContents(True)
        self.input.setAlignment(QtCore.Qt.AlignCenter)
        self.input.setObjectName("input")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(360, 20, 331, 281))
        self.output.setScaledContents(True)
        self.output.setAlignment(QtCore.Qt.AlignCenter)
        self.output.setObjectName("output")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(340, 10, 16, 301))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.images = QtWidgets.QPushButton(self.centralwidget)
        self.images.setEnabled(True)
        self.images.setGeometry(QtCore.QRect(20, 340, 201, 41))
        self.images.setObjectName("images")
        self.videos = QtWidgets.QPushButton(self.centralwidget)
        self.videos.setEnabled(True)
        self.videos.setGeometry(QtCore.QRect(250, 340, 201, 41))
        self.videos.setObjectName("videos")
        self.camera = QtWidgets.QPushButton(self.centralwidget)
        self.camera.setEnabled(True)
        self.camera.setGeometry(QtCore.QRect(480, 340, 201, 41))
        self.camera.setObjectName("camera")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input.setText(_translate("MainWindow", "显示原始图片"))
        self.output.setText(_translate("MainWindow", "检测结果"))
        self.images.setText(_translate("MainWindow", "图片检测"))
        self.videos.setText(_translate("MainWindow", "视频检测"))
        self.camera.setText(_translate("MainWindow", "摄像头检测"))
